package xyz.vprolabs.sparrow.mixin.Utils;

import net.minecraft.client.texture.Sprite;
import net.minecraft.client.texture.SpriteContents;
import net.minecraft.util.Identifier;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.gen.Invoker;

/**
 * Sprite's constructor is protected (vanilla builds sprites only inside the
 * stitcher callback). The atlas cache must construct sprites at load time,
 * with x/y/w/h matching the stitched layout so UVs and the per-sprite mip
 * views are byte-identical to a fresh vanilla reload.
 *
 * Constructor @Invokers are OBJECT_FACTORYs: Mixin REQUIRES the interface
 * method to be static (the generated bytecode is NEW + INVOKESPECIAL, no
 * receiver). A non-static declaration fails the whole Sprite class
 * transformation, which makes Sprite.class unloadable and blacks out every
 * texture in the game.
 *
 * The static body is javac-only scaffolding: Mixin rewrites invokestatic
 * calls to this method from other mixin classes (accessorMixins owner
 * rewrite in MixinTargetContext.transformMethodRef) to the generated static
 * method in Sprite, so the body never executes. UnsupportedOperationException
 * (an Exception, not an Error) guarantees a missed rewrite degrades to the
 * caller's catch (Exception) -> vanilla fallback instead of a crash.
 */
@Mixin(Sprite.class)
public interface SpriteInvoker {

    @Invoker("<init>")
    static Sprite invokeInit(Identifier atlasId, SpriteContents contents, int x, int y, int width, int height, int padding) {
        throw new UnsupportedOperationException("Mixin should have rewritten this static factory call to Sprite.invokeInit");
    }
}
